/**
 * \file
 *
 * \brief Autogenerated API include file for the AVR Software Framework (ASF)
 *
 * Copyright (C) 2011 Atmel Corporation. All rights reserved.
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 * from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 * Atmel AVR product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 */

#ifndef ASF_H
#define ASF_H

/*
 * This file includes all API header files for the selected drivers from ASF.
 *
 * The file is automatically generated and will be re-written when
 * running the ASF driver selector tool. Any changes will be discarded.
 */

#include <print.h>
#include <fileIO.h>
#include <AltBlckQ.h>
#include <AltPollQ.h>
#include <partest.h>
#include <comtest.h>
#include <countsem.h>
#include <crflash.h>
#include <GenQTest.h>
#include <crhook.h>
#include <PollQ.h>
#include <mevents.h>
#include <death.h>
#include <semtest.h>
#include <dynamic.h>
#include <BlockQ.h>
#include <blocktim.h>
#include <recmutex.h>
#include <AltBlock.h>
#include <AltQTest.h>
#include <flash.h>
#include <IntQueue.h>
#include <QPeek.h>
#include <serial.h>
#include <comtest2.h>
#include <flop.h>
#include <integer.h>
#include <intc.h>
#include <queue.h>
#include <croutine.h>
#include <FreeRTOS.h>
#include <projdefs.h>
#include <list.h>
#include <task.h>
#include <StackMacros.h>
#include <mpu_wrappers.h>
#include <timers.h>
#include <semphr.h>
#include <portable.h>
#include <power_clocks_lib.h>
#include <sleep.h>
#include <gpio.h>
#include <usart.h>
#include <tc.h>

#include <stdio_usb.h>
#endif // ASF_H
